
-----------------------------------------------
<m:top name='模块管理' c='6,' display='block'>
    <m:item name='模块管理' link='module_main.php' rank='sys_module' target='main' />
    <m:item name='上传新模块' link='module_upload.php' rank='sys_module' target='main' />
    <m:item name='模块生成向导' link='module_make.php' rank='sys_module' target='main' />
    </m:top>
<m:top item='7' name='辅助插件' display='block'>
  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />
  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />
<m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />
<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />
<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />
<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />
<m:item name='投票模块' link='vote_main.php' rank='plus_投票模块' target='main' />

</m:top>

<m:top name='采集侠' c='1,' display='block' rank=''>
<m:item name='基本设置' link='cjx.php?ac=setting' rank='' target='main' />
<m:item name='高级设置' link='cjx.php?ac=advanced' rank='' target='main' />
<m:item name='伪原创设置' link='cjx.php?ac=seo' rank='' target='main' />
<m:item name='搜索优化设置' link='cjx.php?ac=search' rank='' target='main' />
<m:item name='采集任务' link='cjx.php?ac=task' rank='' target='main' />
<m:item name='超级采集' link='cjx.php?ac=advcjx' rank='' target='main' />
<m:item name='在线更新' link='cjx.php?ac=update' rank='' target='main' />
<m:item name='我的授权' link='cjx.php?ac=credits' rank='' target='main' />
<m:item name='帮助中心' link='http://www.dedeapps.com/Related/?plugin=caijixia' rank='' target='main' />
</m:top>
<m:top name='百度站内搜索' c='6,' display='block' rank=''>
  <m:item name='站内搜索' link='baidusitemap_main.php' rank='' target='main' />
  <m:item name='搜索框管理' link='baidusitemap_main.php?dopost=searchbox2' rank='' target='main' />
  <m:item name='结果页管理' link='baidusitemap_main.php?dopost=searchpage2' rank='' target='main' />
  <m:item name='获得收入' link='baidusitemap_main.php?dopost=income2' rank='' target='main' />  
  <m:item name='数据报表' link='baidusitemap_main.php?dopost=report2' rank='' target='main' />
</m:top>







-----------------------------------------------
