<?php
$z[0]=Array("noteinfo","",2,205);
$z[0][4]['notename']="Ê±ÉĞ";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="https://www.xineee.com/lifestyle/travel//20180416134.html";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}https://www.xineee.com/lifestyle/travel/{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"sec-main fl\">{/dede:areastart}\r\n    {dede:areaend}<div class=\"list-page\">{/dede:areaend}\r\n",209,721);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="https://www.xineee.com/lifestyle/travel/list_22_(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="10000";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']=".html";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>