
<m:item name='基本设置' link='cjx.php?ac=setting' rank='' target='main' />
<m:item name='高级设置' link='cjx.php?ac=advanced' rank='' target='main' />
<m:item name='伪原创设置' link='cjx.php?ac=seo' rank='' target='main' />
<m:item name='搜索优化设置' link='cjx.php?ac=search' rank='' target='main' />
<m:item name='采集任务' link='cjx.php?ac=task' rank='' target='main' />
<m:item name='超级采集' link='cjx.php?ac=advcjx' rank='' target='main' />
<m:item name='在线更新' link='cjx.php?ac=update' rank='' target='main' />
<m:item name='我的授权' link='cjx.php?ac=credits' rank='' target='main' />
<m:item name='帮助中心' link='http://www.dedeapps.com/Related/?plugin=caijixia' rank='' target='main' />
