
  <m:item name='站内搜索' link='baidusitemap_main.php' rank='' target='main' />
  <m:item name='搜索框管理' link='baidusitemap_main.php?dopost=searchbox2' rank='' target='main' />
  <m:item name='结果页管理' link='baidusitemap_main.php?dopost=searchpage2' rank='' target='main' />
  <m:item name='获得收入' link='baidusitemap_main.php?dopost=income2' rank='' target='main' />  
  <m:item name='数据报表' link='baidusitemap_main.php?dopost=report2' rank='' target='main' />
